package com.soy.replyrobot.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-12-01T15:40:15.993+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://ws.replyrobot.soy.com/", name = "ReplyRobot")
@XmlSeeAlso({ObjectFactory.class})
public interface ReplyRobot {

    @WebMethod
    @RequestWrapper(localName = "getContent", targetNamespace = "http://ws.replyrobot.soy.com/", className = "com.soy.replyrobot.ws.client.GetContent")
    @ResponseWrapper(localName = "getContentResponse", targetNamespace = "http://ws.replyrobot.soy.com/", className = "com.soy.replyrobot.ws.client.GetContentResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getContent(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getModel", targetNamespace = "http://ws.replyrobot.soy.com/", className = "com.soy.replyrobot.ws.client.GetModel")
    @ResponseWrapper(localName = "getModelResponse", targetNamespace = "http://ws.replyrobot.soy.com/", className = "com.soy.replyrobot.ws.client.GetModelResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.soy.replyrobot.ws.client.Command getModel(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
